- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v11.0.0
  hooks:
    - id: clang-format
      files: \.(c|h)$

- repo: https://github.com/diffplug/spotless
  rev: v4.0.0
  hooks:
    - id: cppcheck
      name: cppcheck
      entry: cppcheck --enable=all --inconclusive --xml --xml-version=2
      files: \.(c|h)$
